alter table public.admin_users
  add column if not exists auth_user_id uuid
  references auth.users (id) on delete set null;

drop index if exists public.admin_users_auth_user_id_unique;
create unique index admin_users_auth_user_id_unique
  on public.admin_users (auth_user_id)
  where auth_user_id is not null;

alter table public.admin_users
  drop constraint if exists admin_users_role_check;

update public.admin_users
set role = 'superadmin'
where role = 'owner';

alter table public.admin_users
  add constraint admin_users_role_check
  check (role in ('superadmin', 'admin', 'facilitator', 'viewer'));

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_admin_user_id bigint references public.admin_users (id) on delete set null,
  actor_auth_user_id uuid,
  actor_name text not null check (char_length(actor_name) between 1 and 80),
  actor_email text not null check (char_length(actor_email) between 3 and 254),
  actor_role text not null
    check (actor_role in ('superadmin', 'admin', 'facilitator', 'viewer')),
  action text not null check (char_length(action) between 1 and 80),
  resource_type text not null check (char_length(resource_type) between 1 and 80),
  resource_id text,
  summary text not null check (char_length(summary) between 1 and 500),
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);

create index if not exists admin_audit_logs_actor_idx
  on public.admin_audit_logs (actor_admin_user_id, created_at desc);

create index if not exists admin_audit_logs_resource_idx
  on public.admin_audit_logs (resource_type, resource_id, created_at desc);

alter table public.admin_audit_logs enable row level security;

revoke all on table public.admin_audit_logs from anon, authenticated;
revoke all on sequence public.admin_audit_logs_id_seq from anon, authenticated;
grant all on table public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq to service_role;

comment on table public.admin_audit_logs is
  'Immutable application audit trail for authenticated admin actions.';
