create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 254),
  role text not null default 'facilitator'
    check (role in ('owner', 'admin', 'facilitator', 'viewer')),
  status text not null default 'invited'
    check (status in ('active', 'invited', 'suspended')),
  last_active_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admin_users_email_unique
  on public.admin_users (lower(email));

create index if not exists admin_users_status_role_idx
  on public.admin_users (status, role);

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row execute function private.set_updated_at();

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on sequence public.admin_users_id_seq from anon, authenticated;
grant all on table public.admin_users to service_role;
grant usage, select on sequence public.admin_users_id_seq to service_role;

insert into public.admin_users
  (name, email, role, status, last_active_at)
values
  (
    'Alicia Tan',
    'alicia@naviwealth.app',
    'owner',
    'active',
    now() - interval '8 minutes'
  ),
  (
    'Marcus Lee',
    'marcus@naviwealth.app',
    'admin',
    'active',
    now() - interval '2 hours'
  ),
  (
    'Nadia Rahman',
    'nadia@naviwealth.app',
    'facilitator',
    'active',
    now() - interval '1 day'
  ),
  (
    'Ethan Wong',
    'ethan@naviwealth.app',
    'facilitator',
    'invited',
    null
  ),
  (
    'Maya Lim',
    'maya@naviwealth.app',
    'viewer',
    'active',
    now() - interval '4 days'
  )
on conflict do nothing;

create table if not exists public.game_settings (
  id smallint primary key default 1 check (id = 1),
  default_players integer not null default 4
    check (default_players between 2 and 12),
  default_rounds integer not null default 12
    check (default_rounds between 4 and 40),
  starting_balance integer not null default 25000
    check (starting_balance between 1000 and 1000000),
  turn_seconds integer not null default 60
    check (turn_seconds between 15 and 600),
  market_volatility text not null default 'balanced'
    check (market_volatility in ('low', 'balanced', 'high')),
  auto_rotate_events boolean not null default true,
  allow_negative_balance boolean not null default false,
  enable_loans boolean not null default true,
  require_facilitator boolean not null default true,
  updated_by text not null default 'System',
  updated_at timestamptz not null default now()
);

drop trigger if exists game_settings_set_updated_at on public.game_settings;
create trigger game_settings_set_updated_at
before update on public.game_settings
for each row execute function private.set_updated_at();

alter table public.game_settings enable row level security;

revoke all on table public.game_settings from anon, authenticated;
grant all on table public.game_settings to service_role;

insert into public.game_settings (id)
values (1)
on conflict (id) do nothing;
